### ISSUE TITLE
Make ZipRunFromDirectory post deployment validation optional and Configurable

### ISSUE THREAD

**Issue by devlead** [cake-contrib/Cake.Kudu.Client#1]
As brought up by  @markheath in response to [“Run-From-Zip” with Cake Kudu Client](https://hackernoon.com/run-from-zip-with-cake-kudu-client-5c063cd72b37) post and Azure/app-service-announcements-discussions#32 the post deployment doesn't work for some web project types.

Therefor validation should be optional or configurable and an overload will be added for that looking someting like this
```cake
string  baseUri     = EnvironmentVariable("KUDU_CLIENT_BASEURI"),
        userName    = EnvironmentVariable("KUDU_CLIENT_USERNAME"),
        password    = EnvironmentVariable("KUDU_CLIENT_PASSWORD");

 IKuduClient kuduClient = KuduClient(
     baseUri,
     userName,
     password);

 DirectoryPath sourceDirectoryPath       = "./Documentation/";
 bool    skipPostDeploymentValidation    = false;
 string  expectedValidateValue           = "1.0.0.0";
 string  relativeValidateUrl             = $"/api/GetVersion?version={expectedValidateValue}";

 FilePath deployFilePath = kuduClient.ZipRunFromDirectory(
                                         sourceDirectoryPath,
                                         skipPostDeploymentValidation,
                                         relativeValidateUrl,
                                         expectedValidateValue);

 Information("Deployed to {0}", deployFilePath);
```

If `skipPostDeploymentValidation` is set to `true` then no post validation will occur.

If `expectedValidateValue` is set then that value will be used to verify deployment, `relativeValidateUrl` gives option to set a relative alternative url used to verify deployment.

**Comment by devlead** [comment]
Fixed by  4091298ff6c90726d3f8953276d883b72d07e384

**Comment by devlead** [comment]
Now available on NuGet https://www.nuget.org/packages/Cake.Kudu.Client/0.5.0

**Comment by markheath** [comment]
awesome, thanks for sorting this so quickly

**Comment by devlead** [comment]
@markheath excellent, `relativeValidateUrl` is great when doing Azure functions btw, I just added a function that returns assembly version and validated against that which is pretty handy .
