### ISSUE TITLE
Breaking changed AppServices RunFromZip app setting & marker filename

### ISSUE THREAD

**Issue by devlead** [cake-contrib/Cake.Kudu.Client#3]
As per feedback from @davidebbo on medium
https://medium.com/@david.ebbo/weve-renamed-a-couple-things-30c80af821e5

> We’ve renamed a couple things:
> 
> App Setting: `WEBSITE_USE_ZIP` --> `WEBSITE_RUN_FROM_ZIP`
> Marker filename: siteversion.txt --> packagename.txt
> Would be great if you can update article accordingly. Thanks!

**Comment by devlead** [comment]
Fixex by 6e0ebcac8ead66614d8e4864a178b7a16ff6fdff

**Comment by davidebbo** [comment]
As an aside, you might want to take a look at https://github.com/Azure/app-service-announcements/issues/110, which would simplify things a bit, and abstract away from some of the details.

**Comment by devlead** [comment]
Interesting, zipdeploy API was already in place before Run-From-Zip😎

Look like a great addition and should just work ootb with the addin👍 Will have to take that for a spin shortly.

Really cool would be if one could set a header or something to zipdeploy so one didn't need to muck around with app settings to utilize Run-From-Zip.

**Comment by davidebbo** [comment]
> Really cool would be if one could set a header or something to zipdeploy so one didn't need to muck around with app settings to utilize Run-From-Zip.

Unfortunately, that's hard to do, because zipdeploy runs in the sandbox, and the sandbox doesn't have the ability to set App Settings. But I hear you that it would be a good goal. OTOH, it's a one-time App Setting to set on the app, so it's not something you need to do on every deployment.

**Comment by devlead** [comment]
Yip, true, regardless good stuff👍
